// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgFRIu1OEP4VE-kGNm7Dc6wsOli_OG4to',
    appId: '1:720084868040:web:fb6ff810ee718f6082befd',
    messagingSenderId: '720084868040',
    projectId: 'hammam-equipo-triana',
    authDomain: 'hammam-equipo-triana.firebaseapp.com',
    storageBucket: 'hammam-equipo-triana.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVTpgLakaNxCKsEycJESDTfkG5-Dq5FHk',
    appId: '1:720084868040:android:ddc58fde165ecd4782befd',
    messagingSenderId: '720084868040',
    projectId: 'hammam-equipo-triana',
    storageBucket: 'hammam-equipo-triana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKr6opG3R0s_ScCeqLTdW350DTxJqqLIU',
    appId: '1:720084868040:ios:0a42d54ae1c4bebf82befd',
    messagingSenderId: '720084868040',
    projectId: 'hammam-equipo-triana',
    storageBucket: 'hammam-equipo-triana.firebasestorage.app',
    iosBundleId: 'com.example.hammamManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKr6opG3R0s_ScCeqLTdW350DTxJqqLIU',
    appId: '1:720084868040:ios:0a42d54ae1c4bebf82befd',
    messagingSenderId: '720084868040',
    projectId: 'hammam-equipo-triana',
    storageBucket: 'hammam-equipo-triana.firebasestorage.app',
    iosBundleId: 'com.example.hammamManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgFRIu1OEP4VE-kGNm7Dc6wsOli_OG4to',
    appId: '1:720084868040:web:71b62e4be58aedce82befd',
    messagingSenderId: '720084868040',
    projectId: 'hammam-equipo-triana',
    authDomain: 'hammam-equipo-triana.firebaseapp.com',
    storageBucket: 'hammam-equipo-triana.firebasestorage.app',
  );
}
